<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Thu Sep 15 21:40:56 CEST 2011.
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for rating entities.
 */
class MUTicket_Entity_Validator_Rating extends MUTicket_Entity_Validator_Base_Rating
{
    // here you can add custom validation methods or override existing checks
}
