<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Sun Sep 11 16:08:57 CEST 2011.
 */


/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for ticket entities.
 */
class MUTicket_Entity_Validator_Ticket extends MUTicket_Entity_Validator_Base_Ticket
{
    // here you can add custom validation methods or override existing checks
}
