<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de) at Sat Aug 31 12:39:20 CEST 2013.
 */

/**
 * This handler class handles the page events of the Form called by the mUTicket_user_edit() function.
 * It aims on the label object type.
 */
class MUTicket_Form_Handler_User_Label_Edit extends MUTicket_Form_Handler_User_Label_Base_Edit
{
    // feel free to extend the base handler class here
}
