<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Thu Feb 02 13:43:18 CET 2012.
 */

/**
 * The muticketSelectorLabel plugin provides items for a dropdown selector.
 *
 * Available parameters:
 *   - assign:   If set, the results are assigned to the corresponding variable instead of printed out.
 *
 * @param  array            $params  All attributes passed to this function from the template.
 * @param  Zikula_Form_View $view    Reference to the view object.
 *
 * @return string The output of the plugin.
 */
function smarty_function_muticketSelectorLabel($params, $view)
{
    $ticketId = $params['ticket'];
    // we get ticket repository
    $repository = MUTicket_Util_Model::getTicketRepository();
    // we get ticket by Id
    $ticket = $repository->selectById($ticketId);
    // we get labels of ticket
    $ticketLabels = $ticket->getLabelticket();
    if ($ticketLabels != NULL) {
        $existingLabels = array();
        $labelrepository = MUTicket_Util_Model::getLabelRepository();
        foreach ($ticketLabels as $ticketLabel) {
            $thisLabel = $labelrepository->selectById($ticketLabel['id']);
            $existingLabels[] = $thisLabel['id'];
            
        }
    }
    
    $args = array('ot' => 'label', 'orderBy' => 'name ASC');
    
    $labels = ModUtil::apiFunc('MUTicket', 'selection', 'getEntities' , $args);

    $result = array();
    $output = '';
    foreach ($labels as $label) {
        $output .= "<option ";

        $output .= "value='";
        $output .= $label['id'];
        $output .= "'";

        if (in_array($label['id'], $existingLabels)) {
            $output .= " selected=selected";
        }
        $output .= ">";
        $output .= $label['name'];
        $output .= "</option>";
        //$result[] = array('text' => $label['name'], 'value' => $label['id']);
    }

    if (array_key_exists('assign', $params)) {
        $view->assign($params['assign'], $result);
        return;
    }
    return $output;
}
