<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Thu Feb 02 13:43:18 CET 2012.
 */

/**
 * The muticketGetTicketState modifier return the state of a ticket with an image.
 *
 * @param  int       $id      cat id
 *
 * @return string the category name
 */
function smarty_modifier_muticketGetTicketState($id)
{
	// we build a repository
	$repository = MUTicket_Util_Model::getTicketRepository();

	// We check the state of the ticket
	$where = 'tbl.parent_id = ' . DataUtil::formatForStore($id);
	$count = $repository->selectCount($where);
	if ($count == 0) {
		$title = __('New');
		$state = "<img src='modules/MUTicket/images/New.png' title=$title />";
		return $state;
	}

	$serviceManager = ServiceUtil::getManager();
	$em = $serviceManager->getService('doctrine.entitymanager');
	$qb = $em->createQueryBuilder();
	$qb->select('s.createdUserId, s.id')
	->from('MUTicket_Entity_Ticket', 's')
	->where('s.parent_id = :id')
	->setParameter('id', $id)
	->orderBy('s.id', 'DESC');

	$ticket = $qb->getQuery()->getArrayResult();

	$supporteruids = MUTicket_Util_Model::getExistingSupporterUids(0);

	if (in_array($ticket[0]['createdUserId'], $supporteruids)) {
		$title = __('Customer!');
		$state = "<img src='modules/MUTicket/images/Customer.png' title=$title />";
	}
	else {

		$title = __('Supporter!');
		$state = "<img src='modules/MUTicket/images/Supporter.png' title=$title />";
	}

	return $state;
}
