<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de) at Sat Aug 31 12:39:20 CEST 2013.
 */

/**
 * The muticketObjectState modifier displays the name of a given object's workflow state.
 * Examples:
 *    {$item.workflowState|muticketObjectState}       {* with led icon *}
 *    {$item.workflowState|muticketObjectState:false} {* no icon *}
 *
 * @param string  $state    Name of given workflow state.
 * @param boolean $withIcon Whether a led icon should be displayed before the name.
 *
 * @return string Enriched and translated workflow state ready for display.
 */
function smarty_modifier_muticketObjectState($state = 'initial', $withIcon = true)
{
    $serviceManager = ServiceUtil::getManager();
    $workflowHelper = new MUTicket_Util_Workflow($serviceManager);
    $stateInfo = $workflowHelper->getStateInfo($state);

    $result = $stateInfo['text'];
    if ($withIcon === true) {
        $result = '<img src="' . System::getBaseUrl() . 'images/icons/extrasmall/' . $stateInfo['icon'] . '" width="16" height="16" alt="' . $result . '" />&nbsp;&nbsp;' . $result;
    }

    return $result;
}
