<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Wed Jan 11 12:10:27 CET 2012.
 */

/**
 * This handler class handles the page events of the Form called by the MUTicket_user_edit() function.
 * It aims on the rating object type.
 */
class MUTicket_Form_Handler_User_Rating_Edit extends MUTicket_Form_Handler_User_Rating_Base_Edit
{
	/**
	 * (non-PHPdoc)
	 * @see MUTicket_Form_Handler_User_Base_Edit::initializeAdditions()
	 */
    protected function initializeAdditions()
    { 
    	$ticket = $this->request->getGet()->filter('ticket', '', FILTER_SANITIZE_STRING);	
    	$ratingvalue = MUTicket_Util_Controller::getRatingValues();
    	
    	$rating = $this->view->get_template_vars('rating');
     	//$rating['ratingvalueItems'] = $ratingvalue;
     	$this->view->assign('rating', $ratingvalue);
     	$this->view->assign('ticket', $ticket);    	
    }
}
