<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de) at Sat Aug 31 12:39:20 CEST 2013.
 */

/**
 * User field plugin providing an autocomplete for user names.
 *
 * You can also use all of the features from the Zikula_Form_Plugin_TextInput plugin since
 * the user input inherits from it.
 */
class MUTicket_Form_Plugin_UserInput extends MUTicket_Form_Plugin_Base_UserInput
{
    // feel free to add your customisation here
}
