<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Thu Feb 02 13:43:18 CET 2012.
 */

/**
 * The muticketShowRating modifier displays the rating for a ticket answer.
 *
 * @param  int       $id      cat id
 *
 * @return out the html for rating of ticket
 */
function smarty_modifier_muticketShowRating($id)
{
	/**
	 *
	 */

	$serviceManager = ServiceUtil::getManager();
	$handler = new Zikula_Form_View($serviceManager, 'MUTicket');

	$repository = MUTicket_Util_Model::getRatingRepository();
	$where = 'tbl.ticket = \'' . DataUtil::formatForStore($id) . '\'';
	$rating = $repository->selectWhere($where);

	$value = $rating[0]['ratingvalue'];
	$out = $handler->__('You have rated this support answer:') . '<br />';
	for ($i = 0; $i < $value; $i++) {
		$out .= '<img src="images/icons/small/favorites.png" />';
	}

	return $out;
}
