<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Sun Sep 11 16:08:57 CEST 2011.
 */

/**
 * The muticketImageThumb modifier displays a thumbnail image.
 *
 * @param  string    $fileName   The input file name.
 * @param  string    $filePath   The input file path (including file name).
 * @param  int       $width      Desired width.
 * @param  int       $height     Desired height.
 * @param  array     $thumbArgs  Additional arguments.
 *
 * @return string The thumbnail file path.
 */
function smarty_modifier_muticketImageThumb($fileName = '', $filePath = '', $width = 100, $height = 80, $thumbArgs = array())
{
    /**
     * By overriding this plugin or the util method called below you may add further thumbnail arguments
     * based on custom conditions.
     */
    return MUTicket_Util_Image::getThumb($filePath, $width, $height, $thumbArgs);
}
