<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Thu Feb 02 13:43:18 CET 2012.
 */

/**
 * The muticketCatName modifier displays the cat name.
 *
 * @param  int       $id      cat id
 *
 * @return string the category name
 */
function smarty_modifier_muticketCatName($id)
{
    /**
     * 
     */
    $cat = CategoryUtil::getCategoryByID($id);
    
    $lang = ZLanguage::getLanguageCode();
    
    $displayname = $cat['display_name'];
    
    if ($displayname != '') {
    $name = $displayname[$lang];
    }
    else {
     $name = $name['name'];
    }
    
    return $name;
}
