<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Sun Sep 11 16:08:57 CEST 2011.
 */


/**
 * This is the User controller class providing navigation and interaction functionality.
 */
class MUTicket_Controller_User extends MUTicket_Controller_Base_User
{
    /**
     * This method provides a generic item list overview.
     *
     * @param string  $ot           Treated object type.
     * @param string  $sort         Sorting field.
     * @param string  $sortdir      Sorting direction.
     * @param int     $pos          Current pager position.
     * @param int     $num          Amount of entries to display.
     * @param string  $tpl          Name of alternative template (for alternative display options, feeds and xml output)
     * @param boolean $raw          Optional way to display a template instead of fetching it (needed for standalone output)
     * @return mixed Output.
     */
    public function view($args)
    {

        // get state of the link
        $state = $this->request->getGet()->filter('state','', FILTER_SANITIZE_STRING);
        
        $this->view->assign('state', $state);
        
        return parent::view($args);
        
    }
    
    /**
     * This method provides a generic item detail view.
     *
     * @param string  $kind         kind of logged in user - 0 for supporter, 1 for user
     * @return parent display()
     */
    public function display($args)
    {
    	// May the user rate
		$kind = MUTicket_Util_View::userForRating();
		
		$this->view->assign('kind', $kind);
		
		return parent::display($args);
    }
    
}
