<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Thu Jan 05 16:12:14 CET 2012.
 */

/**
 * Selection api implementation class
 */
class MUTicket_Api_Selection extends MUTicket_Api_Base_Selection
{
	/**
    * Select a list of entities by different criteria.
    * @param string  $args['where']    The where clause to use when retrieving the collection (optional) (default='').
    * @return Array with retrieved collection and amount of total records affected by this query.
    */
    public function getEntities($args) {
        
        $args['where'] = MUTicket_Util_View::getTicketClause();
    	
        return parent::getEntities($args);
    }
    
    
    /**
    * Select a list of entities by different criteria.
    *
    * @param string  $args['where']          The where clause to use when retrieving the collection (optional) (default='').
    * @return Array with retrieved collection and amount of total records affected by this query.
    */
    public function getEntitiesPaginated($args)
    {
   	    $args['where'] = MUTicket_Util_View::getTicketClause();
    	
    	return parent::getEntitiesPaginated($args);    	
    	
    }
}
