<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de) at Sat Aug 31 12:39:21 CEST 2013.
 */

/**
 * This class provides object meta data for the Tag module.
 */
class MUTicket_TaggedObjectMeta_MUTicket extends MUTicket_TaggedObjectMeta_Base_MUTicket
{
    // feel free to extend the tag support here
}
