<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Sun Sep 11 16:08:57 CEST 2011.
 */

/**
 * This is the Account api helper class.
 */
class MUTicket_Api_Base_Account extends Zikula_AbstractApi
{
    /**
     * get available Account panel links
     *
     * @return array Array of admin links
     */
    public function getlinks()
    {
        $links = array();

        return $links;
    }
}
