<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Sun Sep 11 16:08:57 CEST 2011.
 */

/**
 * This is the Admin api helper class.
 */
class MUTicket_Api_Base_Admin extends Zikula_AbstractApi
{
    /**
     * get available Admin panel links
     *
     * @return array Array of admin links
     */
    public function getlinks()
    {
        $links = array();

        if (SecurityUtil::checkPermission('MUTicket::', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url('MUTicket', 'admin', 'view', array('ot' => 'ticket')),
                             'text' => $this->__('Tickets'),
                             'title' => $this->__('Ticket list'));
        }
        if (SecurityUtil::checkPermission('MUTicket::', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url('MUTicket', 'admin', 'view', array('ot' => 'rating')),
                             'text' => $this->__('Ratings'),
                             'title' => $this->__('Rating list'));
        }
        if (SecurityUtil::checkPermission('MUTicket::', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url('MUTicket', 'admin', 'view', array('ot' => 'supporter')),
                             'text' => $this->__('Supporters'),
                             'title' => $this->__('Supporter list'));
        }
        if (SecurityUtil::checkPermission('MUTicket::', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url('MUTicket', 'admin', 'config'),
                             'text' => $this->__('Configuration'),
                             'title' => $this->__('Manage settings for this application'));
        }
        return $links;
    }
}
