<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Thu Sep 15 21:40:56 CEST 2011.
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the base validation class for ticket entities.
 */
class MUTicket_Entity_Validator_Base_Ticket extends MUTicket_Validator
{

    /**
     * Performs all validation rules.
     *
     * @return mixed either array with error information or true on success
     */
    public function validateAll()
    {
        $errorInfo = array('message' => '', 'code' => 0, 'debugArray' => array());
        $dom = ZLanguage::getModuleDomain('MUTicket');
        if (!$this->isStringNotLongerThan('title', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('title', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('text', 2000)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('text', 2000), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('images', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('images', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('files', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('files', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isValidBoolean('state')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid boolean (%s).', array('state'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidBoolean('t_rating')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid boolean (%s).', array('t_rating'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidBoolean('rated')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid boolean (%s).', array('rated'), $dom);
            return $errorInfo;
        }
        return true;
    }

    /**
     * Check for unique values.
     *
     * This method determines if there already exist tickets with the same ticket.
     *
     * @param string $fieldName The name of the property to be checked
     * @return boolean result of this check, true if the given ticket does not already exist
     */
    public function isUniqueValue($fieldName)
    {
        if (empty($value)) {
            return false;
        }

        $serviceManager = ServiceUtil::getManager();
        $entityManager = $serviceManager->getService('doctrine.entitymanager');
        $repository = $entityManager->getRepository('MUTicket_Entity_Ticket');

        $excludeid = $this->entity['id'];
        return $repository->detectUniqueState($fieldName, $this->entity[$fieldName], $excludeid);
    }

    /**
     * Get entity.
     *
     * @return Zikula_EntityAccess
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * Set entity.
     *
     * @param Zikula_EntityAccess $entity.
     *
     * @return void
     */
    public function setEntity(Zikula_EntityAccess $entity = null)
    {
        $this->entity = $entity;
    }

}
