
<?php
/**
 * MUTicket.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUTicket
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Sun Sep 11 16:08:57 CEST 2011.
 */


/**
 * Configuration handler implementation class
 */
class MUTicket_Form_Handler_Admin_Config extends MUTicket_Form_Handler_Base_Admin_Config
{
    protected function initializeAdditions()
    {
    	//  make dropdownlist for supporter groups
    
    	ModUtil::dbInfoLoad('Groups');
    	$tables = DBUtil::getTables();
    	
    	//get groups for the config menue
    	  	
    	$groups = DBUtil::selectObjectArray('groups');
    	if ($groups == false) {
    		LogUtil::registerError($this->__('Error! No groups available!'), 404);
    	}
    	
    	$supportgroups = array();
    	
    	foreach ($groups as $group)  {
    	$supportgroups[] = array('value' => $group['name'], 'text' => $group['name']);
    	}

    	$config = $this->view->get_template_vars('config');
     	$config['supportergroupItems'] = $supportgroups;
     	$this->view->assign('config', $config);

    }
}
